
on:
  push:
    branches:
      - 'dev-test-release'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-release:
    name: create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          draft: ${{ ! github.ref.startWith('refs/tags/') }}
          # draft: true
          release_name: Release ${{ github.ref_name }}

  release:
    name: release
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        release_name: [glad-2.0.6]
    steps:
      - uses: actions/checkout@v1

      - name: Prepare distridution
        run: |
          mkdir -p ${{ matrix.release_name }}
          cp generate.bat generate.sh meson_options.txt meson.build ${{ matrix.release_name }}

      - name: Zip
        run: tar -zcvf glad-meson-patch-${{ matrix.release_name }}.tar.gz ${{ matrix.release_name }}/

      - name: upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./glad-meson-patch-${{ matrix.release_name }}.tar.gz
          asset_name: glad-meson-patch-${{ matrix.release_name }}.tar.gz
          asset_content_type: application/gzip

      - name: create glad.wrap
        run: |
          sed -e "s|patch_url =|patch_url = ${{ steps.upload_release_asset.outputs.browser_download_url }}|; s|patch_hash = |patch_hash = $(shasum -a 256 glad-meson-patch-${{ matrix.release_name }}.tar.gz | cut -d ' ' -f 1)|" glad.wrap.template > glad.wrap
      
      - name: upload glad.warp
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./glad.wrap
          asset_name: glad.wrap
          asset_content_type: text/plain